config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", :as => :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  root "home#index"
  get "about", to: "home#about"

  get "signup", to: "users#new"
  post "signup", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # Users management (full CRUD)
  resources :users do
    member do
      get "change_password"
      patch "update_password"
      post "impersonate"
    end
  end

  # Inspections
  resources :inspections do
    collection do
      get "search"
      get "overdue"
    end
    member do
      get "certificate"
      get "qr_code"
    end
  end

  # Images admin
  get "images/all", to: "images#all"
  get "images/orphaned", to: "images#orphaned"

  # Short URL for certificates
  get "c/:id", to: "inspections#certificate", as: "short_certificate"
  get "C/:id", to: "inspections#certificate", as: "short_certificate_uppercase"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :inspections, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: {with: URI::MailTo::EMAIL_REGEXP}
  validates :password, presence: true, length: {minimum: 6}, if: :password_digest_changed?
  validates :inspection_limit, numericality: {only_integer: true, greater_than_or_equal_to: -1}

  before_create :set_default_inspection_limit
  before_create :set_admin_if_first_user
  before_save :downcase_email

  def can_create_inspection?
    inspection_limit == -1 || inspections.count < inspection_limit
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def set_default_inspection_limit
    env_limit = ENV["LIMIT_INSPECTIONS"]
    self.inspection_limit = env_limit.present? ? env_limit.to_i : 10
  end

  def set_admin_if_first_user
    self.admin = User.count.zero?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :require_admin, only: [:index, :edit, :update, :destroy, :impersonate]
  before_action :set_user, only: [:edit, :update, :destroy, :change_password, :update_password, :impersonate]
  before_action :require_correct_user, only: [:change_password, :update_password]

  def index
    @users = User.includes(:inspections).all
    @total_images = ActiveStorage::Attachment.where(record_type: "Inspection", name: "image").count
    @orphaned_images = ActiveStorage::Blob.left_joins(:attachments).where(active_storage_attachments: {id: nil}).count
    @active_jobs = {
      storage_cleanup: {
        name: "StorageCleanupJob",
        scheduled: StorageCleanupJob.scheduled?,
        last_run: StorageCleanupJob.last_run_at,
        next_run: StorageCleanupJob.next_run_at
      }
    }
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      if Rails.env.production?
        NtfyService.notify("new user: #{@user.email}")
      end

      log_in @user
      flash[:success] = "Account created"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User updated"
      redirect_to users_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  def change_password
  end

  def update_password
    if @user.authenticate(params[:user][:current_password])
      if @user.update(password_params)
        flash[:success] = "Password updated"
        redirect_to root_path
      else
        render :change_password, status: :unprocessable_entity
      end
    else
      @user.errors.add(:current_password, "is incorrect")
      render :change_password, status: :unprocessable_entity
    end
  end

  def impersonate
    log_in @user
    flash[:success] = "You are now impersonating #{@user.email}"
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    if current_user&.admin?
      params.require(:user).permit(:email, :password, :password_confirmation, :inspection_limit)
    else
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end

  # Using require_admin from ApplicationController

  def require_correct_user
    unless current_user == @user
      flash[:danger] = "You can only change your own password"
      redirect_to root_path
    end
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def admin_status(user)
    user.admin? ? "Yes" : "No"
  end

  def inspection_count(user)
    count = user.inspections.count
    "#{count} #{(count == 1) ? "inspection" : "inspections"}"
  end

  def format_job_time(time)
    return "Never" unless time
    "#{time_ago_in_words(time)} ago"
  end
end

app/views/users/change_password.html.erb
<header>
  <h1>Change Password</h1>
</header>

<%= form_with(model: @user, url: update_password_user_path(@user), method: :patch, local: true) do |form| %>
  <% if @user.errors.any? %>
    <aside>
      <h3><%= pluralize(@user.errors.count, "error") %> prevented your password from being changed:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </aside>
  <% end %>

  <%= form.label :current_password %>
  <%= form.password_field :current_password %>

  <%= form.label :password, "New Password" %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation, "Confirm New Password" %>
  <%= form.password_field :password_confirmation %>

  <%= form.submit "Update Password" %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<header>
  <h1>Edit User</h1>
</header>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <aside>
      <h3><%= pluralize(@user.errors.count, "error") %> prevented this user from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </aside>
  <% end %>


  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password, "New Password (leave blank if no change)" %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <% if current_user.admin? %>
    <%= form.label :inspection_limit %>
    <%= form.number_field :inspection_limit, min: 0 %>
  <% end %>

  <%= form.submit "Update User" %>
<% end %>

<% if @user != current_user %>
  <article>
    <%= button_to "Log in as #{@user.email}", impersonate_user_path(@user), method: :post, 
        data: { confirm: "You will be logged in as #{@user.email}. You'll need to log out to return to your admin account." } %>
  </article>
  <article>
    <%= button_to "Delete", user_path(@user), method: :delete, data: { confirm: "Are you sure?" } %>
  </article>
<% end %>

app/views/users/index.html.erb
<article class="users">
  <header><h1>Users</h1></header>
  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>Admin</th>
        <th>Registered</th>
        <th>Last Active</th>
        <th>Inspections</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.email, edit_user_path(user) %></td>
          <td><%= user.admin? ? "Yes" : "No" %></td>
          <td title="<%= user.created_at.strftime('%d/%m/%Y') %>">
            <%= time_ago_in_words(user.created_at) %>
          </td>
          <% if user.last_active_at %>
            <td title="<%= user.last_active_at.strftime('%d/%m/%Y') %>">
              <%= time_ago_in_words(user.last_active_at) %>
            </td>
          <% else %>
            <td>Never</td>
          <% end %>
          <td><%= user.inspections.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <hr>
  <h2>Images</h2>
  <p>Total images: <%= link_to @total_images, images_all_path %></p>
  <p>Orphaned images: <%= link_to @orphaned_images, images_orphaned_path %></p>
  <hr>
  <h2>Background Jobs</h2>
  <table>
   <thead>
      <tr>
        <th>Job</th>
        <th>Last Run</th>
        <th>Next Run</th>
      </tr>
    </thead>
    <tbody>
      <% @active_jobs.each do |key, job| %>
        <tr>
          <td><%= job[:name] %></td>
          <td><%= job[:last_run] ? time_ago_in_words(job[:last_run]) + " ago" : "Never" %></td>
          <td><%= job[:next_run] ? time_ago_in_words(job[:next_run]) + " from now" : "Not scheduled" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</article>

app/views/users/new.html.erb
<%= form_with(model: @user, url: signup_path) do |form| %>
  <header>
    <h1>Register</h1>
  </header>

  <% if @user.errors.any? %>
    <aside>
      <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      <ul>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
      </ul>
    </aside>
  <% end %>


  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.submit "Register" %>
<% end %>